name: szeretet_foldje
description: This is a small app, collecting a displaying news from my fater's website.

version: 1.1.0+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  share:
  fluttertoast:
  stream_transform:
  path_provider: ^1.1.0
  sqflite: ^1.1.5
  html: ^0.13.3
  flutter_html: ^0.9.6
  rxdart: ^0.18.0
  http: 0.12.0+1
  url_launcher: "5.0.2"
  connectivity:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "lib/ui/normal_logo.png"
  android: true
  ios: false

flutter:
  uses-material-design: true